name: FirstYAML

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  run:
    runs-on: windows-latest
    # Set the timeout for this step to 10 minutes
    timeout-minutes: 120
    #Set the CML container
    #container:docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Model Training
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python SectionA.py
          echo "# Results" > README.md
          cat results.txt >> report.md




