name: FirstYAML

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    # Set the timeout for this step to 10 minutes
    timeout-minutes: 120
    #Set the CML container
    #container:docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Model Training
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python Machine_Learning_Code.py
      -name:Get CML Report Results
        env:
            REPO_TOKEN:${{secrets.GITHUB_TOKEN}}
        run: |
          echo "# Results" > report.md
          cat results.txt >> report.md
          echo ':{}(./actual_vs_predicted.png "Predicted vs Actual")'>>report.md
          cml comment create report.md



